[font]
size = 12.0

[font.bold]
family = "Luxi Mono"
style = "Bold"

[font.bold_italic]
family = "Luxi Mono"
style = "Bold Italic"

[font.italic]
family = "Luxi Mono"
style = "Italic"

[font.normal]
family = "Luxi Mono"
style = "Regular"

[window]
opacity = 0.95

[window.dimensions]
columns = 133
lines = 40
